export const timezoneShortNames: { [key: string]: string } = {
    "America/New_York": "EDT",
    "America/Chicago": "CDT",
    "America/Denver": "MDT",
    "America/Los_Angeles": "PDT",
    "America/Toronto": "EDT",
    "America/Vancouver": "PDT",
    "America/Mexico_City": "CDT",
    "America/El_Salvador": "CST",
    "America/Sao_Paulo": "BRT",
    "Europe/London": "BST",
    "Europe/Paris": "CEST",
    "Europe/Madrid": "CEST",
    "Europe/Berlin": "CEST",
    "Europe/Rome": "CEST",
    "Europe/Amsterdam": "CEST",
    "Europe/Oslo": "CEST",
    "Europe/Stockholm": "CEST",
    "Africa/Johannesburg": "SAST",
    "Asia/Tokyo": "JST",
    "Asia/Seoul": "KST",
    "Asia/Singapore": "SGT",
    "Asia/Dubai": "GST",
    "Asia/Kolkata": "IST",
    "Australia/Sydney": "AEST",
    "Australia/Melbourne": "AEST",
    "Pacific/Auckland": "NZST",
    "Pacific/Honolulu": "HST",
    "Etc/UTC": "UTC",
    // You can add more if needed, but these cover 90% of users 🌎
  };
  